### ISSUE TITLE
One questions

### ISSUE THREAD

**Issue by RizzooTv** [AndrewR3K/bcc-zonealerts#1]
First of all thank you for your work

I have one questions can you make it a little smaller? For example
![Screenshot_404](https://user-images.githubusercontent.com/39269181/170677955-09c05a34-0e41-456e-8aa6-816986f3390a.png)

It looks very big in the game maybe you can make it a little smaller overall

**Comment by AndrewR3K** [comment]
Sure thing! Ill add it to my trello. Ill might add a sizing option within the config.

**Comment by AndrewR3K** [comment]
I have added a NEW native rdr that is exactly what rdr2 uses. I have also made the custom notification an option still and made it smaller if you end up still using that part.

Cheers! 🥂
